# TCL File Generated by Component Editor 17.0
# Thu Nov 09 20:47:34 CET 2017
# DO NOT MODIFY


# 
# data_gen "data_gen" v1.1
# Strahinja Jankovic 2017.11.09.20:47:34
# Simple data generation component
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module data_gen
# 
set_module_property DESCRIPTION "Simple data generation component"
set_module_property NAME data_gen
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Strahinja Jankovic"
set_module_property DISPLAY_NAME data_gen
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL data_gen
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file data_gen.vhd VHDL PATH data_gen.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point bus
# 
add_interface bus avalon end
set_interface_property bus addressUnits WORDS
set_interface_property bus associatedClock clock
set_interface_property bus associatedReset reset
set_interface_property bus bitsPerSymbol 8
set_interface_property bus burstOnBurstBoundariesOnly false
set_interface_property bus burstcountUnits WORDS
set_interface_property bus explicitAddressSpan 0
set_interface_property bus holdTime 0
set_interface_property bus linewrapBursts false
set_interface_property bus maximumPendingReadTransactions 0
set_interface_property bus maximumPendingWriteTransactions 0
set_interface_property bus readLatency 0
set_interface_property bus readWaitTime 1
set_interface_property bus setupTime 0
set_interface_property bus timingUnits Cycles
set_interface_property bus writeWaitTime 0
set_interface_property bus ENABLED true
set_interface_property bus EXPORT_OF ""
set_interface_property bus PORT_NAME_MAP ""
set_interface_property bus CMSIS_SVD_VARIABLES ""
set_interface_property bus SVD_ADDRESS_GROUP ""

add_interface_port bus bus_address address Input 8
add_interface_port bus bus_read read Input 1
add_interface_port bus bus_readdata readdata Output 32
add_interface_port bus bus_write write Input 1
add_interface_port bus bus_writedata writedata Input 32
add_interface_port bus bus_waitrequest waitrequest Output 1
set_interface_assignment bus embeddedsw.configuration.isFlash 0
set_interface_assignment bus embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment bus embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment bus embeddedsw.configuration.isPrintableDevice 0


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint bus
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq irq Output 1

